#ifndef TALAPIVR_H
#define TALAPIVR_H
/* Generated by buildRevFileP4.py */
/* Information extracted from ../.././components/talapi/p4codeline.xml */
/* P4 Path : //CAK/components/talapi/TAGS/TALAPI_1_4_4 */
/* Last version: TALAPI_1_4_4 */
#define TALAPI_RELEASE "1.4.4"
#define TALAPI_NAME "TALAPI"
#define TALAPI_VERSION 001004004
#define TALAPI_BRANCH 000000
#define TALAPI_CANDIDATE 000
#endif /* TALAPIVR_H */
