#pragma once

namespace {
const auto PROJECT_NAME { "${PROJECT_NAME}" };
const auto PROJECT_DESCRIPTION { "${PROJECT_DESCRIPTION}" };
const auto PROJECT_VERSION_MAJOR { "${PROJECT_VERSION_MAJOR}" };
const auto PROJECT_VERSION_MINOR { "${PROJECT_VERSION_MINOR}" };
const auto PROJECT_VERSION_PATCH { "${PROJECT_VERSION_PATCH}" };
const auto PROJECT_VERSION_TWEAK { "${PROJECT_VERSION_TWEAK}" };
const auto PROJECT_VERSION_HEX { "${PROJECT_VERSION_HEX}" };
const auto PROJECT_COMPILE_TIMESTAMP { "${PROJECT_COMPILE_TIMESTAMP}" };
const auto PROJECT_BUILD_TYPE { "${CMAKE_BUILD_TYPE}" };
}
