# Note: Buildroot's and Meson's terminologies differ about the meaning
# of 'build', 'host' and 'target':
# - Buildroot's 'host' is Meson's 'build'
# - Buildroot's 'target' is Meson's 'host'

[binaries]
c = '/opt/ali/buildroot-10.2.1.29/output/host/bin/mips-mti-linux-gnu-gcc'
cpp = '/opt/ali/buildroot-10.2.1.29/output/host/bin/mips-mti-linux-gnu-g++'
ar = '/opt/ali/buildroot-10.2.1.29/output/host/bin/mips-mti-linux-gnu-gcc-ar'
strip = '/opt/ali/buildroot-10.2.1.29/output/host/bin/mips-mti-linux-gnu-strip'
cmake = '/opt/ali/buildroot-10.2.1.29/output/host/bin/cmake'
pkgconfig = '/opt/ali/buildroot-10.2.1.29/output/host/bin/pkgconf'
g-ir-compiler = '/opt/ali/buildroot-10.2.1.29/output/host/mipsel-buildroot-linux-gnu/sysroot/usr/bin/g-ir-compiler'
g-ir-scanner = '/opt/ali/buildroot-10.2.1.29/output/host/mipsel-buildroot-linux-gnu/sysroot/usr/bin/g-ir-scanner'

[built-in options]
c_args = ['-D_LARGEFILE_SOURCE', '-D_LARGEFILE64_SOURCE', '-D_FILE_OFFSET_BITS=64', '-Os', '-g0', '-flto']
c_link_args = []
cpp_args = ['-D_LARGEFILE_SOURCE', '-D_LARGEFILE64_SOURCE', '-D_FILE_OFFSET_BITS=64', '-Os', '-g0', '-flto']
cpp_link_args = []
wrap_mode = 'nodownload'
cmake_prefix_path = '/opt/ali/buildroot-10.2.1.29/output/host/mipsel-buildroot-linux-gnu/sysroot/usr/lib/cmake'

[properties]
needs_exe_wrapper = true
sys_root = '/opt/ali/buildroot-10.2.1.29/output/host/mipsel-buildroot-linux-gnu/sysroot'
pkg_config_libdir = '/opt/ali/buildroot-10.2.1.29/output/host/mipsel-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig:/opt/ali/buildroot-10.2.1.29/output/host/mipsel-buildroot-linux-gnu/sysroot/usr/share/pkgconfig'
pkg_config_static = 'false'

[host_machine]
system = 'linux'
cpu_family = 'mips'
cpu = ''
endian = 'little'
