#pragma once

#define STREAM_TYPE_11172_VIDEO         0x01
#define STREAM_TYPE_13818_VIDEO         0x02
#define STREAM_TYPE_11172_AUDIO         0x03
#define STREAM_TYPE_13818_AUDIO         0x04
#define STREAM_TYPE_PRIVATE_DATA        0x05
#define STREAM_TYPE_VC1_VIDEO           0xEA    // VC1
#define STREAM_TYPE_14496_2_VIDEO       0x10    // MPEG4
#define STREAM_TYPE_14496_10_VIDEO      0x1B    // H264
#define STREAM_TYPE_AVS_VIDEO           0x42    // AVS
#define STREAM_TYPE_HEVC_VIDEO          0x24    // HEVC
#define STREAM_TYPE_H264_VIDEO          0x27    // HEVC
#define STREAM_TYPE_13818_7_AUDIO       0x0F    // AAC
#define STREAM_TYPE_14496_3_AUDIO       0x11    // AAC
#define STREAM_TYPE_AC3_AUDIO           0x81    // AC3
#define STREAM_TYPE_SCTE                0x82    // TS packets containing SCTE data
#define STREAM_TYPE_DTS_AUDIO           0x82    // DTS
#define STREAM_TYPE_DOLBY_TRUEHD_AUDIO  0x83    // dolby true HD

#define STREAM_TYPE_PRIVATE             0x06    // PES packets containing private data

#define VIDEO_STREAM_DESCRIPTOR 0x02
#define AUDIO_STREAM_DESCRIPTOR 0x03
#define HIERACHY_DESCRIPTOR 0x04
#define REGISTRATION_DESCRIPTOR 0x05
#define DATA_STREAM_ALIGNMENT_DESCRIPTOR 0x06
#define TARGET_BACKGROUND_GRID_DESCRIPTOR 0x07
#define VIDEO_WINDOW_DESCRIPTOR 0x08
#define CA_DESCRIPTOR 0x09
#define LANGUAGE_DESCRIPTOR 0x0A
#define SYSTEM_CLOCK_DESCRIPTOR 0x0B
#define MULTIPLEX_BUFFER_USAGE_DESCRIPTOR 0x0C
#define COPYRIGHT_DESCRIPTOR 0x0D
#define MAXIMUM_BITRATE_DESCRIPTOR 0x0E
#define PRIVATE_DATA_INDICATOR_DESCRIPTOR 0x0F
#define SMOOTHING_BUFFER_DESCRIPTOR 0x10
#define STD_DESCRIPTOR 0x11
#define IBP_DESCRIPTOR 0x12

// From https://en.wikipedia.org/wiki/Program-specific_information
#define VIDEO_STREAM_HEADER_H264 0x28 // Video stream header parameters for ITU-T Rec. H.264 and ISO/IEC 14496-10
#define SYSTEM_CLOCK_EXTERNAL_REFERENCE 0x0B // System clock external reference
#define MAXIMUM_BIT_RATE 0x0E // Maximum bit rate
#define SMOOTHING_BUFFER 0x10 // Smoothing buffer
#define AUDIO_STREAM_HEADER_MPEG4 0x1C // Audio stream header parameters for ISO/IEC 14496-3 (MPEG-4 LOAS multi-format framed)
#define AUDIO_STREAM_HEADER_AAC 0x7C
#define DRM_DESCRIPTOR 0x7f // ISO/IEC 13818-11 IPMP (DRM)

#define NETWORK_NAME_DESCRIPTOR 0x40
#define SERVICE_LIST_DESCRIPTOR 0x41
#define STUFFING_DESCRIPTOR 0x42
#define SATELLITE_DELIVERY_DESCRIPTOR 0x43
#define CABLE_DELIVERY_DESCRIPTOR 0x44
#define BOUQUET_NAME_DESCRIPTOR 0x47
#define SERVICE_DESCRIPTOR 0x48
#define COUNTRY_AVAILABILITY_DESCRIPTOR 0x49
#define LINKAGE_DESCRIPTOR 0x4A
#define NVOD_REFERENCE_DESCRIPTOR 0x4B
#define TIME_SHIFTED_SERVICE_DESCRIPTOR 0x4C
#define SHORT_EVENT_DESCRIPTOR 0x4D
#define EXTENDED_EVENT_DESCRIPTOR 0x4E
#define TIME_SHIFTED_EVENT_DESCRIPTOR 0x4F
#define COMPONENT_DESCRIPTOR 0x50
#define MOSAIC_DESCRIPTOR 0x51
#define STREAM_IDENTIFIER_DESCRIPTOR 0x52
#define CA_IDENTIFIER_DESCRIPTOR 0x53
#define CONTENT_DESCRIPTOR 0x54
#define PARENTAL_RATING_DESCRIPTOR 0x55
#define TELETEXT_DESCRIPTOR 0x56
#define TELEPHONE_DESCRIPTOR 0x57
#define LOCAL_TIME_OFFSET_DESCRIPTOR 0x58
#define SUBTITLING_DESCRIPTOR 0x59
#define TERRESTRIAL_DELIVERY_DESCRIPTOR 0x5A
#define MULTILINGUAL_NETWORK_NAME_DESCRIPTOR 0x5B
#define MULTILINGUAL_BOUQUET_NAME_DESCRIPTOR 0x5C
#define MULTILINGUAL_SERVICE_NAME_DESCRIPTOR 0x5D
#define MULTILINGUAL_COMPONENT_DESCRIPTOR 0x5E
#define PRIVATE_DATA_SPECIFIER_DESCRIPTOR 0x5F
#define SERVICE_MOVE_DESCRIPTOR 0x60
#define SHORT_SMOOTHING_BUFFER_DESCRIPTOR 0x61
#define FREQUENCY_LIST_DESCRIPTOR 0x62
#define PARTIAL_TRANSPORT_STREAM_DESCRIPTOR 0x63
#define DATA_BROADCAST_DESCRIPTOR 0x64
#define CA_SYSTEM_DESCRIPTOR 0x65
#define DATA_BROADCAST_ID_DESCRIPTOR 0x66
#define TRANSPORT_STREAM_DESCRIPTOR 0x67
#define DSNG_DESCRIPTOR 0x68
#define PDC_DESCRIPTOR 0x69
#define AC3_DESCRIPTOR 0x6A
#define S2_SATELLITE_DELIVERY_SYSTEM_DESCRIPTOR 0x79
#define AC3_PLUS_DESCRIPTOR 0x7A
#define ANCILLARY_DATA_DESCRIPTOR 0x6B
#define CELL_LIST_DESCRIPTOR 0x6C
#define CELL_FREQUENCY_LINK_DESCRIPTOR 0x6D
#define ANNOUNCEMENT_SUPPORT_DESCRIPTOR 0x6E

#define AC3_EXT_DESCRIPTOR 0x52

#define CAPTION_SERVICE_DESCRIPTOR 0x86

#define MAX_PMT_LEN     1024

#define CA_REPLACEMENT_SERVICE 0x03
#define LINKAGE_TYPE_SW_UPDATE 0x09

/********* TVRO CLARO ***************************/
#define SINALIZACAO_DOS_CANAIS_NAO_REGIONALIZADOS 0x82
#define SINALIZACAO_DOS_CANAIS_REGIONALIZADOS 0xE6
#define UD_TVRO_LINKAGE_ZONE_ID 0xFE
#define CLARO_OTA_TSPID (6041) //(0x06FE)
#define SKY_OTA_TSPID (6045)

/********* SKY ***************************/
#define UD_SKY_LOGICAL_CHANNEL_DESCRIPTOR 0xE2
#define UD_SKY_SERVICE_ORDER_LIST_DESCRIPTOR 0xE4

/***********TS PID defintion**************/

#define PAT_TSPID (0x0000)
#define CAT_TSPID (0x0001)
#define NIT_TSPID (0x0010)
#define EIT_TSPID (0x0012)
#define TOT_TSPID (0x0014)
#define TDT_TSPID (0x0014)
#define SDT_TSPID (0x0011)
#define BAT_TSPID (0x0011)

#define INVALID_TSPID (0x1fff)

/***********Table ID defintion**************/
#define PAT_TABLE_ID (0x00)
#define OTA_TABLE_ID (0x3B)
#define CAT_TABLE_ID (0x01)
#define PMT_TABLE_ID (0x02)
#define NIT_TABLE_ID_ACTUAL (0x40)
#define NIT_TABLE_ID_OTHER (0x41)

#define SDT_TABLE_ID_ACTUAL (0x42)
#define SDT_TABLE_ID_OTHER (0x46)

#define BAT_TABLE_ID (0x4A)
#define EIT_TABLE_ID_PF_ACTUAL (0x4E)
#define EIT_TABLE_ID_PF_OTHER (0x4F)
#define EIT_TABLE_ID_SCHEDULE_ACTUAL_LOW (0x50)
#define EIT_TABLE_ID_SCHEDULE_ACTUAL_HIGH (0x5F)

#define EIT_TABLE_ID_SCHEDULE_OTHER_LOW (0x60)
#define EIT_TABLE_ID_SCHEDULE_OTHER_HIGH (0x6F)

#define TDT_TABLE_ID (0x70)
#define TOT_TABLE_ID (0x73)

#define DSI_TABLE_ID (0x3B)
#define DDB_TABLE_ID (0x3C)
#define SKYWORTH_OTA_HEADER_TABLE_ID (0x91)

/***********BOUQUET_ID - SKY defintion**************/
#define BOUQUET_ID (0x61A8)

namespace mb {

inline int bcd2dec(int bcd)
{
    return ((bcd >> 4) * 10) + bcd % 16;
}

};
