/**
** @file nv_info.h
**
** @brief
**   DVR/VOD Library Credential, system & chipset information functions.
**
**   The syntax of the comments of this file is compliant to the format used by
**   Doxygen to generate html documentation from source and header files.
**   Doxygen can be downloaded from www.doxygen.org and is provided under GNU
**   General Public License.
**
** $Revision:  $
**
** Copyright:
**   2006-2017 Nagra India
**
**
*/


#ifndef NV_INFO_H
#define NV_INFO_H

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/*																			  */
/*								 INCLUDE FILES								  */
/*																			  */
/******************************************************************************/

#include "nv_pvr.h"


/******************************************************************************/
/*																			  */
/*									   TYPES								  */
/*																			  */
/******************************************************************************/

/**
 *  @ingroup groupCredInfo
 *  @brief
 *    Defines the maximum length of the device ID string
 *
*/
#define MAX_OUTPUT_DEVICE_ID_SIZE  256

/**
 *  @ingroup groupSystemInfo
 *  @brief
 *    defines the length of the string version of the DVR/VOD Library.
 *
 *  @see  TDvlVersionString
*/
#define DVL_VERSION_STRING_LENGTH  20

/**
 *  @ingroup groupSystemInfo
 *  @brief
 *    This type is used for NULL-terminated printable string containing the
 *    version of the DVR/VOD Library.
*/
typedef TChar TDvlVersionString[DVL_VERSION_STRING_LENGTH];

/**
 *  @ingroup groupSystemInfo
 *  @brief
 *    defines the length of the unique ID string.
 *
 *  @see  TDvlUniqueIdString
*/
#define DVL_UNIQUE_ID_STRING_LENGTH  16

/**
 *  @brief
 *    This type is used for NULL-terminated printable strings containing a Nagra
 *    Unique identifier, such as the chipset unique ID (the NUID) or the IRD S/N.
 *    It respects the following format: "xx xxxx xxxx xx".
*/
typedef TChar TDvlUniqueIdString[DVL_UNIQUE_ID_STRING_LENGTH];

/**
 *  @ingroup groupSystemInfo
 *  @brief
 *    defines the length of the chipset type string.
 *
 *  @see  TDvlChipsetTypeString
*/
#define DVL_CHIPSET_TYPE_STRING  40

/**
 *  @ingroup groupSystemInfo
 *  @brief
 *    This type is used for NULL-terminated printable strings containing a
 *    chipset type. It respects the following format:
 *    "xxxx xxxx xxxx xxxx xx".
*/
typedef TChar TDvlChipsetTypeString[DVL_CHIPSET_TYPE_STRING];

/**
 *  @ingroup groupCredInfo
 *  @brief
 *    The output format of the Credentials information request depends on the
 *    type of Credentials. Current known Credentials types are:
 *    - VOD EMM: Credentials generated by the Head End and containing the key
 *      protecting the consumption rules associated to a VOD content. VOD EMM
 *      can be processed only by the decoder to which they are intended.
 *    - VOD ECM: Credentials generated by the Head End and containing the key
 *      protecting the VOD content.
 *    - LCM: Credentials generated by the DVR/VOD Library at recording time.
 *      It contains the key protecting the recorded content and its
 *      consumption rules. LCM can be used for playback only by the decoder
 *      that recorded the content.
*/
typedef enum
{
  CREDENTIALS_TYPE_PROFILE = 0,
    /**<  Deprecated.
     *    The Credentials correspond to a Profile.
    */
  CREDENTIALS_TYPE_VOD_EMM,
    /**<  The Credentials correspond to a VOD EMM.\n
     *    This field is not applicable for DVL Dual Library.
    */
  CREDENTIALS_TYPE_VOD_ECM,
    /**<  The Credentials correspond to a VOD content.\n
     *    This field is not applicable for DVL Dual Library.
    */
  CREDENTIALS_TYPE_LCM,
    /**<  The Credentials correspond to a LCM.
    */
  CREDENTIALS_TYPE_HOME_NETWORK_LCM,
    /**<  Deprecated.
     *    The Credentials correspond to a Home Network LCM.
     *    This type is deprecated and never supported.
    */
  CREDENTIALS_TYPE_HOME_DOMAIN_LCM,
    /**<
     *    The Credentials correspond to a Home Domain Locally Created Message.\n
     *    This field is not applicable for DVL Dual Library.
     *
    */
  CREDENTIALS_TYPE_UNKNOWN,
    /**<  The Credentials are of unknown type.
    */
  LAST_CREDENTIALS_TYPE
    /**<  Last Credentials type value.
     *    This value is never returned by the DVR/VOD Library.
    */
} TCredentialsType;

/**
 *  @ingroup groupCredInfo
 *  @brief
 *  This indicates Root Of Trust (ROT) of the device.
 */
typedef enum
{
  LCM_ROT_TYPE_SKL      = 0x05,
    /**<
     *    Indicates that the Root Of Trust is Software Key Ladder
    */
  LCM_ROT_TYPE_TKL      = 0x06,
    /**<
     *    Indicates that the Root Of Trust is Third party Key Ladder
    */
  LCM_ROT_TYPE_NOCS     = 0x07,
    /**<
     *    Indicates that the Root Of Trust is Nagra On Chip Security
    */
  LCM_ROT_TYPE_UNKNOWN  = 0xFF
} TDvlLcmRotType;

/**
 *  @deprecated
 *  This structure is deprecated.
 *  @ingroup groupCredInfo
 *  @brief
 *    This structure contains all public information contained into Credentials
 *    of type CREDENTIALS_TYPE_PROFILE.
*/
typedef struct
{
  TUnsignedInt32            profileId;
    /**<
     *    Unique identifier of the Profile.
    */
  TUnsignedInt16            profileVersion;
    /**<
     *    Version of the Profile.
    */
  TUnixDate                 credentialsCreationDate;
    /**<
     *    Date at which the Profile has been created.
    */
  TUnixDate                 profileExpirationDate;
    /**<
     *    Date at which the Profile expires. Corresponds to the date after
     *    which no content can anymore be recorded using that Profile.
    */
  TViewingWindowRelativity  contentViewingWindowRelativity;
    /**<
     *    Relativity of the viewing window.
     *    @see ::TViewingWindowRelativity
    */
  TCaDuration               contentViewingWindowDuration;
    /**<
     *    Number of seconds the content recorded with help of this Profile can
     *    be played back.\n
     *    The viewing window can be relative to the recording date or to the
     *    content first visualization date.
    */
  TCaDuration               contentRetentionDuration;
    /**<
     *    Number of seconds the content recorded with help of this Profile can
     *    be stored on the HDD. It corresponds to the number of seconds after
     *    which the content expires.
    */
} TProfileData;

/**
 *  @note
 *    This structure is not applicable for DVL Dual Library.
 *  @ingroup groupCredInfo
 *  @brief
 *    This structure contains all public information contained into Credentials
 *    of type CREDENTIALS_TYPE_VOD_EMM.\n
 *    Once \c contentViewingWindowEndDate is reached, the STB application shall
 *    remove the related content from the HDD.\n
 *    If the viewing window is relative to the recording date (the
 *    \c credentialsCreationDate), the \c contentViewingWindowEndDate
 *    corresponds to the \c contentExpirationDate. If the viewing window is
 *    relative to the first content visualization, the
 *    \c contentViewingWindowEndDate is smaller or equal to the
 *    \c contentExpirationDate.
*/
typedef struct
{
  TUnsignedInt32            irdSerialNumber;
    /**<
     *    Unique identifier of the STB for which the credentials is intended.
    */
  TUnsignedInt32            contentId;
    /**<
     *    Unique identifier of the VOD content as Integer value.
    */
  TUnsignedInt32            vodEmmId;
    /**<
     *    Unique identifier of the VOD EMM.
    */
  TUnixDate                 credentialsCreationDate;
    /**<
     *    Date at which the VOD EMM has been created. That date corresponds to
     *    the purchase date.
    */
  TUnixDate                 contentExpirationDate;
    /**<
     *    Date at which the VOD content expires.\n
     *    Corresponds to the date after which the related content can no more
     *    be played back, regardless of the \c viewingWindowEndDate.
    */
  TCaDuration               contentViewingWindowDuration;
    /**<
     *    Number of seconds the content can be played back.\n
     *    The viewing window can be relative to the purchase date or to the
     *    content first visualization date.
    */
  TUnixDate                 contentFirstVisualizationDate;
    /**<
     *    Date of the first visualization of the VOD content.\n
     *    - If the related VOD content has not yet been watched,
     *    \c contentFirstVisualizationDate is set to 0xFFFFFFFF.
     *    - If the related VOD content is not encrypted (contentIsCiphered is
     *    set to FALSE), \c contentFirstVisualizationDate is not relevant and is
     *    also set to 0xFFFFFFFF.
    */
  TUnixDate                 contentViewingWindowEndDate;
    /**<
     *    Date after which the VOD content can no more be viewed.
    */
  TViewingWindowRelativity  contentViewingWindowRelativity;
    /**<
     *    Relativity of the viewing window.
     *    @see ::TViewingWindowRelativity
    */
  TBoolean                  contentIsCiphered;
    /**<
     *   - TRUE:   The VOD content is protected and encrypted.
     *   - FALSE:  The VOD content is not encrypted (it's a free content).
    */
  TBoolean                  contentKeyIsProtected;
    /**<
     *    - TRUE:   The content key is protected.\n
     *    - FALSE:  The content key is not protected.
    */
  TUnsignedInt32            nuidValue;
    /**<
     *    NUID of the entity to which the VOD EMM is intended.
    */
  TSize                     contentIdDataSize;
    /**<
     *     Size in Bytes of the buffer containing the
     *     contentIdData
    */
  TChar*                    contentIdData;
    /**<
     *     UTF-8 encoded String representing the
     *     unique identifier of the content.\n
     *     This field is NULL if not available.\n
     *     This buffer will be de-allocated by the DVR/VOD Library
     *     when the related TVodEmmData structure will be freed.
    */
  TSize                     keyIdSize;
    /**<
     *     Size in Bytes of the buffer containing the Identifier
     *     of the content key
    */
  TUnsignedInt8*            pkeyId;
    /**<
     *     Buffer containing the Identifier of the content key.\n
     *     This field is NULL if not available.\n
     *     This buffer will be de-allocated by the DVR/VOD Library
     *     when the related TVodEmmData structure will be freed.
    */
} TVodEmmData;

/**
 *  @note
 *    This structure is not applicable for DVL Dual Library.
 *  @ingroup groupCredInfo
 *  @brief
 *    This structure contains all public information contained into Credentials
 *    of type CREDENTIALS_TYPE_VOD_ECM.
 *    Once \c contentExpirationDate is reached, the STB application shall remove
 *    the related content from the HDD.
*/
typedef struct
{
  TUnsignedInt32            contentId;
    /**<
     *    Unique identifier of the VOD content as Integer value.
    */
  TUnixDate                 contentCreationDate;
    /**<
     *    Date at which the VOD content has been created.
    */
  TUnixDate                 contentExpirationDate;
    /**<
     *    Date at which the content expires.\n
     *    Corresponds to the date after which the related content can no more
     *    be played back, regardless of the \c viewingWindowEndDate.\n
     *    Once this date is reached, the STB application shall remove the
     *    related content from the HDD.
    */
  TUnsignedInt16            contentEmi;
    /**<
     *    Encryption Method Indicator describing the encryption format used for
     *    the VOD content.
    */
  TBoolean                  contentKeyIsProtected;
    /**<
     *    - TRUE:   The content key is protected.
     *    - FALSE:  The content key is not protected.
    */
  TSize                     contentIdDataSize;
    /**<
     *     Size in Bytes of the buffer containing the
     *     contentIdData
    */
  TChar*                    contentIdData;
    /**<
     *     UTF-8 encoded String representing the
     *     unique identifier of the content.\n
     *     This field is NULL if not available.\n
     *     This buffer will be de-allocated by the DVR/VOD Library
     *     when the related TVodEcmData structure will be freed.
    */
  TSize                     keyIdSize;
    /**<
     *     Size in Bytes of the buffer containing the Identifier
     *     of the content key
    */
  TUnsignedInt8*            pkeyId;
    /**<
     *     Buffer containing the Identifier of the content key.\n
     *     This field is NULL if not available.\n
     *     This buffer will be de-allocated by the DVR/VOD Library
     *     when the related TVodEcmData structure will be freed.
    */
} TVodEcmData;

/**
 *  @ingroup groupCredInfo
 *  @brief
 *    This structure contains all public information contained into Credentials
 *    of type CREDENTIALS_TYPE_LCM.\n
 *    Once \c contentViewingWindowEndDate is reached, the STB application shall
 *    remove the related content from the HDD.
*/
typedef struct
{
  TUnsignedInt32            irdSerialNumber;
    /**<
     *    Unique identifier of the STB that created the LCM.
     *    For non NOCS devices, this value will be set to 0xFFFFFFFF.
    */
  TUnsignedInt32            profileId;
    /**<  Deprecated.
     *    Unique identifier of the Profile that was used to create the LCM.
    */
  TUnsignedInt32            collectionId;
    /**<  Unique identifier of the collection to which belongs the content
     *    protected by this LCM. In order to be able to append two contents,
     *    they must belong to the same collection.
    */
  TUnixDate                 credentialsCreationDate;
    /**<
     *    Date at which the LCM has been created.
     *    Corresponds to the content recording date.
    */
  TUnixDate                 contentExpirationDate;
    /**<
     *    Date at which the content expires.\n
     *    Corresponds to the date after which the related content can no longer
     *    be played back, regardless of the \c contentViewingWindowEndDate.
     *    Once this date is reached, the STB application shall remove the related
     *    content from the HDD.
    */
  TCaDuration               contentViewingWindowDuration;
    /**<
     *    Number of seconds the content can be played back.\n
     *    The viewing window can be relative to the record date or to the
     *    content first visualization date.
    */
  TUnixDate                 contentFirstVisualizationDate;
    /**<
     *    Date of the first visualization of the content.\n
     *    If the related content has not yet been watched,
     *    \c contentFirstVisualizationDate is set to 0xDEADBEEF.
    */
  TUnixDate                 contentViewingWindowEndDate;
    /**<
     *    Date after which the content can no more be viewed with this LCM.
    */
  TUnixDate                 contentAppendEndDate;
    /**<
     *    Deprecated.
     *    Date until another content can be appended to this content. In order
     *    to be able to append two contents, they must belong to the same
     *    collection.
    */
  TViewingWindowRelativity  contentViewingWindowRelativity;
    /**<
     *    Relativity of the viewing window.
     *    @see ::TViewingWindowRelativity
    */
  TDvlAccessStatus          contentAccessStatus;
    /**<
     *  \c DVL_ACCESS_GRANTED:
     *        The access to the related content is granted at the current time.
     *        If the \c irdSerialNumber of the LCM differs from the IRD S/N
     *        of the Set-Top Box previously returned by
     *        \c dvlSystemInformationRequest(), it means the Set-Top Box is
     *        able to access content recorded by the decoder identified by the
     *        LCM address.<br>
     *  \c DVL_ACCESS_DENIED_CONTENT_EXPIRED:
     *        The access to the related content is expired.<br>
     *  \c DVL_ACCESS_DENIED_UNKNOWN_STB:
     *        The access to the related content is denied at the current time,
     *        because it has been recorded by an unknown set-top box, identified
     *        by the address of the LCM.<br>
     *  \c DVL_ACCESS_DENIED_UNKNOWN_NUID:
     *        The access to the related content is denied at the current time,
     *        because it has been recorded by an unknown chipset, identified
     *        by the address of the LCM.<br>
     *  \c DVL_ACCESS_DENIED_INVALID_EMI:
     *        The access to the related content is denied at the current time,
     *        because it has been recorded with an EMI unsupported by the SEC
     *        implementation.<br>
     *  \c DVL_ACCESS_DENIED_INVALID_KEY_PROTECTION:
     *        The access to the related content is denied at the current time,
     *        because its key has been protected with a mechanism not
     *        supported by the SEC implementation.
     */
  TUnsignedInt16            contentEmi;
    /**<
     *    Encryption Method Indicator describing the encryption of the content.
     */
  TUnsignedInt32            nuidValue;
    /**<
     *    NUID of the entity that created the LCM.
     *    For non NOCS devices, this field will be set to 0xFFFFFFFF.
    */
  TDvlChipsetTypeString     chipsetType;
    /**<
     *    Type of the chipset that created the LCM.
     *    For non NOCS devices, this field will be empty.
    */
  TDvlLcmRotType            lcmRotType;
    /**<
     *    RoT type of the LCM.
    */
  TSize                     deviceIdSize;
    /**<
     *    Size of the device ID.
     *    This field is applicable for TKL devices only. (Currently supported by dvl dual only)
     *    For NOCS devices, value of this field is equal to the size of irdSerialNumber.
    */
  TUnsignedInt8             deviceId[MAX_OUTPUT_DEVICE_ID_SIZE];
    /**<
     *    Device Identifier.
     *    This field is applicable for TKL devices only. (Currently supported by dvl dual only)
     *    For NOCS devices, value of this field is equal to the irdSerialNumber.
    */
} TLcmData;

/**
 *  @note
 *    This structure is not applicable for DVL Dual Library.
 *  @ingroup groupCredInfo
 *  @brief
 *    This structure contains all public information contained into Credentials
 *    of type CREDENTIALS_TYPE_HOME_DOMAIN_LCM.
*/
typedef struct
{
  TUnsignedInt8 homeDomainNameSize;
  /**<
    *    Size of the Home Domain name associated to the HLCM.
    */
  TUnsignedInt8 * homeDomainName;
   /**<
    *    the Home Domain name associated to the HLCM.
    *     This buffer will be de-allocated by the DVR/VOD Library
    *     when the related THlcmData structure will be freed.
    */
   TUnsignedInt32 homeDomainKeyIndex;
   /**<
    *    Home Domain key index associated to the HLCM.
    */
  TSize                     contentIdDataSize;
    /**<
     *     Size in Bytes of the buffer containing the
     *     contentId
    */
  TChar*                    contentIdData;
    /**<
     *     UTF-8 encoded String representing the
     *     unique identifier of the content.\n
     *     This buffer will be de-allocated by the DVR/VOD Library
     *     when the related THlcmData structure will be freed.
    */
  TSize                     keyIdSize;
    /**<
     *     Size in Bytes of the buffer containing the Identifier
     *     of the content key
    */
  TUnsignedInt8*            pkeyId;
    /**<
     *     Buffer containing the Identifier of the content key.\n
     *     This field is NULL if not available.\n
     *     This buffer will be de-allocated by the DVR/VOD Library
     *     when the related THlcmData structure will be freed.
    */
  TUnixDate                 credentialsCreationDate;
    /**<
     *    Date at which the HLCM has been created.
     *    Corresponds also to the recording date.
    */
  TUnixDate                 contentExpirationDate;
    /**<
     *    Date at which the content expires.
     *    Corresponds to the date after which the related content can no more
     *    be played back.
     *    Once this date is reached, the STB application shall remove the
     *    related content from the HDD.
    */
  TDvlAccessStatus          contentAccessStatus;
    /**<
     *    \c DVL_ACCESS_GRANTED:
     *        The access to the related content is granted at the current time.
     *
     *    \c DVL_ACCESS_DENIED_CONTENT_EXPIRED:
     *        The access to the related content is expired.<br>
     *    \c DVL_ACCESS_DENIED_INVALID_EMI:
     *        The access to the related content is denied at the current time,
     *        because it has been protected with an EMI unsupported by the SEC
     *        implementation.<br>
     *    \c DVL_ACCESS_DENIED_INVALID_KEY_PROTECTION:
     *        The access to the related content is denied at the current time,
     *        because its key has been protected with a mechanism not
     *        supported by the SEC implementation.
     *    \c DVL_ACCESS_DENIED_UNKNOWN_HOME_NETWORK:
     *        The access to the related content is denied at the current time,
     *        because the STB does not belong to the related home domain.
     *    \c DVL_ACCESS_DENIED_MISSING_CREDENTIALS:
     *        The access to the related content is denied because of missing home domain key.
     */
  TUnsignedInt16            contentEmi;
    /**<
     *     Encryption Method Indicator describing the encryption of the content.
     */
  TSize                    standardUsageRulesSize;
    /**<
     *     Size of the standard Usage Rules.
     */
  TUnsignedInt8*           pStandardUsageRules;
    /**<
     *     Standard Usage Rules.
     *     This buffer will be de-allocated by the DVR/VOD Library
     *     when the related THlcmData structure will be freed.
     */
  TSize                    operatorUsageRulesSize;
    /**<
     *     Size of the operator Usage Rules.
     */
  TUnsignedInt8*           pOperatorUsageRules;
    /**<
     *     Operator Usage Rules.
     *     This buffer will be de-allocated by the DVR/VOD Library
     *     when the related THlcmData structure will be freed.
     */
} THlcmData;

/**
 *  @deprecated
 *  This structure is deprecated.
 *  @ingroup groupCredInfo
 *  @brief
 *    This structure contains all public information contained into Credentials
 *    of type CREDENTIALS_TYPE_HOME_NETWORK_LCM.
*/
typedef struct
{
  TUnsignedInt32            irdSerialNumber;
    /**<
     *    Unique identifier of the STB that created the HLCM.
    */
  TUnsignedInt32            homeNetworkId;
    /**<
     *    Unique identifier of the Home Network to which the HLCM belongs.
    */
  TUnsignedInt32            profileId;
    /**<
     *    Unique identifier of the Profile that was used to create the HLCM.
    */
  TUnsignedInt32            collectionId;
    /**<
     *    Unique identifier of the collection to which belongs the content
     *    protected by this HLCM. In order to be able to append two contents,
     *    they must belong to the same collection.
    */
  TUnixDate                 credentialsCreationDate;
    /**<
     *    Date at which the HLCM has been created.
     *    Corresponds also to the recording date.
    */
  TUnixDate                 contentExpirationDate;
    /**<
     *    Date at which the content expires.
     *    Corresponds to the date after which the related content can no more
     *    be played back, regardless of the \c viewingWindowEndDate.
     *    Once this date is reached, the STB application shall remove the
     *    related content from the HDD.
    */
  TCaDuration               contentViewingWindowDuration;
    /**<
     *    Number of seconds the content can be played back.
     *    The viewing window can be relative to the record date or to the
     *    content first visualization date.
    */
  TUnixDate                 contentFirstVisualizationDate;
    /**<
     *    Date of the first visualization of the content.
     *    If the related content has not yet been watched,
     *    \c contentFirstVisualizationDate is set to 0xFFFFFFFF.
    */
  TUnixDate                 contentViewingWindowEndDate;
    /**<
     *    Date after which the content can no more be viewed.
     *    If the viewing window is relative to the recording date (as to know
     *    the \c credentialsCreationDate), the \c viewingWindowEndDate
     *    corresponds to \c credentialsCreationDate + \c viewingWindowDuration.
     *    If the viewing window is relative to the first content visualization,
     *    the \c viewingWindowEndDate is equal to
     *    \c firstVisualizationDate + \c viewingWindowDuration.
    */
  TUnixDate                 contentAppendEndDate;
    /**<
     *    Date until another content can be appended to this content. In order
     *    to be able to append two contents, they must belong to the same
     *    collection.
    */
  TViewingWindowRelativity  contentViewingWindowRelativity;
    /**<
     *    Relativity of the viewing window.
    */
  TDvlAccessStatus          contentAccessStatus;
    /**<
     *    \c DVL_ACCESS_GRANTED:
     *        The access to the related content is granted at the current time.
     *        If the \c irdSerialNumber of the LCM differs from the IRD S/N
     *        of the Set-Top Box previously returned by \c dvlInitialziation(),
     *        that means the Set-Top Box is granted to access content recorded
     *        by the decoder identifier by the LCM \c irdSerialNumber.<br>
     *    \c DVL_ACCESS_DENIED_CONTENT_EXPIRED:
     *        The access to the related content is expired.<br>
     *    \c DVL_ACCESS_DENIED_UNKNOWN_HOME_NETWORK:
     *        The access to the related content is denied at the current time,
     *        because it has been recorded by a set-top box belonging to an
     *        unknown Home Network, identified by the \c homeNetworkId of the
     *        HLCM.
     */
} THomeNetworkLcmData;

/**
 *  @ingroup groupCredInfo
 *  @brief
 *    The output format of the Credentials information request depends on the
 *    type of Credentials. The information of the Credentials is therefore
 *    returned in the form of a union. The content of the union returned by
 *    \c dvlCredentialsInformationRequest() depends on the output
 *    \c *pxCredentialsType parameter.
*/
typedef union
{
  TProfileData          profileData;
    /**<  Deprecated \n
     *    If the Credentials are of type \c CREDENTIALS_TYPE_PROFILE,
     *    their information will be stored into the \c profileData.
    */
  TVodEmmData           vodEmmData;
    /**<  This field is not applicable for DVL Dual Library.\n
     *    If the Credentials are of type \c CREDENTIALS_TYPE_VOD_EMM,
     *    their information will be stored into the \c vodEmmData.
    */
  TVodEcmData           vodEcmData;
    /**<  This field is not applicable for DVL Dual Library.\n
     *    If the Credentials are of type \c CREDENTIALS_TYPE_VOD_ECM,
     *    their information will be stored into the \c vodEcmData.
    */
  TLcmData              lcmData;
    /**<
     *    If the Credentials are of type \c CREDENTIALS_TYPE_LCM,
     *    their information will be stored into the \c lcmData.
    */
  THomeNetworkLcmData   homeNetworkLcmData;
    /**<  Deprecated \n
     *    Not used, kept in order to avoid retro-compatibility issue.
     *
    */
  THlcmData   hlcmData;
    /**<  This field is not applicable for DVL Dual Library.\n
     *    If the Credentials are of type \c CREDENTIALS_TYPE_HOME_DOMAIN_LCM,
     *    their information will be stored into the \c hlcmData.
    */

} TCredentialsUnion;

/**
 *  @ingroup groupSystemInfo
 *  @brief
 *    This structure contains information specific to the chipset.
*/
typedef struct
{
  TUnsignedInt32            nuidValue;
    /**<
     *    NUID of the chipset.
    */
  TDvlUniqueIdString        nuidString;
    /**<
     *    NULL-terminated and printable string containing the Nagra unique
     *    identifier of the chipset.
    */
  TDvlChipsetTypeString     type;
    /**<
     *    This field contains the chipset type as a NULL-terminated string.
   */
} TDvlChipsetInfo;


/******************************************************************************/
/*                          DVR/VOD API LIBRARY                               */
/******************************************************************************/
/******************************************************************************/
/*                                                                            */
/*                            FUNCTIONS PROTOTYPES                            */
/*                                                                            */
/******************************************************************************/

/**
 *  @ingroup groupSystemInfo
 *  @brief
 *    This function allows the STB application to request information about
 *    DVR/VOD Library.
 *
 *  @pre
 *    The DVR/VOD Library must be running.
 *
 *  @param[out] xVersionString
 *            NULL-terminated string of maximum length
 *            DVL_VERSION_STRING_LENGTH Bytes, containing the project name,
 *            project version and DVR/VOD Library version.
 *  @param[out] pxIrdSerialNumberValue
 *            Value of the Nagra unique identifier of the Set-Top Box on which
 *            runs the DVR/VOD Library.
 *  @param[out] xIrdSerialNumberString
 *            NULL-terminated and printable string containing the Nagra unique
 *            identifier of the Set-Top Box on which runs the DVR/VOD Library.
 *  @param[out] pxNuidValue
 *            Value of the Nagra unique identifier of the chipset.
 *  @param[out] xNuidString
 *            NULL-terminated and printable string containing the Nagra unique
 *            identifier of the chipset.
 *
 *  @retval DVL_NO_ERROR
 *            The function execution was successful.
 *  @retval DVL_ERROR
 *            The function execution failed.
 *  @retval DVL_ERROR_BAD_PARAMETER
 *            One of the input pointers of the function is invalid.
 *  @retval DVL_ERROR_DVL_NOT_RUNNING
 *            The function could not be executed as the DVR/VOD Library is not
 *            running.
*/
NAGRA_CA_API TDvlStatus dvlSystemInformationRequest
(
  TDvlVersionString   xVersionString,
  TUnsignedInt32*    pxIrdSerialNumberValue,
  TDvlUniqueIdString  xIrdSerialNumberString,
  TUnsignedInt32*    pxNuidValue,
  TDvlUniqueIdString  xNuidString
);

/**
 *  @ingroup groupSystemInfo
 *  @brief
 *    This function allows the STB application to request information about
 *    the chipset the DVR/VOD Library was compiled for.
 *
 *  @pre
 *    The DVR/VOD Library must be running.
 *
 *  @param[out] ppxChipsetInformation
 *            Pointer on a static structure of the DVR/VOD Library containing
 *            the chipset information.
 *
 *  @retval DVL_NO_ERROR
 *            The function execution was successful.
 *  @retval DVL_ERROR
 *            The function execution failed.
 *  @retval DVL_ERROR_BAD_PARAMETER
 *            One of the input pointers of the function is invalid.
 *  @retval DVL_ERROR_DVL_NOT_RUNNING
 *            The function could not be executed as the DVR/VOD Library is not
 *            running.
*/
NAGRA_CA_API TDvlStatus dvlChipsetInformationRequest
(
  TDvlChipsetInfo**   ppxChipsetInformation
);

/**
 *  @ingroup groupCredInfo
 *  @brief
 *    This function allows the STB application to request information about
 *    DVR/VOD Library Credentials.
 *    This information returned by this request depends on the type of
 *    Credentials.
 *
 *    Some Credentials may contain operator specific data. As these data are
 *    operator dependant and are not interpreted by the DVR/VOD Library, these
 *    specific data are returned by this request in the form of a buffers of
 *    Bytes pointed by \c *ppxGenericMetadata  and \c *ppxSpecificMetadata.
 *    The STB manufacturer shall refer to the operator for the format and
 *    meaning of the information contained in these metadata.
 *    All output pointers shall be released by the function
 *    \c dvlReleaseBuffer().
 *
 *  @pre
 *    The DVR/VOD Library must be running.
 *
 *  @post
 *    None
 *
 *  @param[in] xCredentialsSize
 *            Size in Bytes of the buffer containing the Credentials.
 *  @param[in] pxCredentials
 *            Pointer to the buffer containing the Credentials.
 *  @param[out] pxCredentialsType
 *            Pointer where the DVR/VOD Library will store the Credentials
 *            type.
 *  @param[out] ppxCredentialsUnion
 *            Pointer where the DVR/VOD Library will store the Credentials
 *            information.
 *            The input pointer shall not be NULL.
 *  @param[out] pxGenericMetadataSize
 *            Pointer where the DVR/VOD Library will store the size of the
 *            optional generic metadata. The input pointer shall not be NULL
 *            if ppxGenericMetadata is not NULL.
 *  @param[out] ppxGenericMetadata
 *            Pointer where the DVR/VOD Library will store the pointer to the
 *            buffer containing the optional generic metadata. This buffer can
 *            be NULL if the caller is not interested in retrieving generic
 *            metadata.
 *            Once the function returns, \c *ppxGenericMetadata may be NULL if
 *            the input Credentials contain no generic metadata or if they are
 *            not valid (function returns \c DVL_ERROR_BAD_PARAMETER).
 *            If returned, the buffer pointed by \c *ppxGenericMetadata shall be
 *            released once no longer used by the STB application, by calling
 *            \c dvlReleaseBuffer().
 *  @param[out] pxSpecificMetadataSize
 *            Pointer where the DVR/VOD Library will store the size of the
 *            optional specific metadata. The input pointer shall not be \c NULL
 *            if \c ppxSpecificMetadata is not \c NULL.
 *  @param[out] ppxSpecificMetadata
 *            Pointer where the DVR/VOD Library will store the pointer to the
 *            buffer containing the optional specific metadata. This buffer can
 *            be NULL if the caller is not interested in retrieving specific
 *            metadata.
 *            Once the function returns, \c *ppxSpecificMetadata may be NULL if
 *            the input Credentials contain no specific metadata or if they are
 *            not valid (function returns \c DVL_ERROR_BAD_PARAMETER).
 *            The buffer pointed by \c *ppxSpecificMetadata shall be released once
 *            no longer used by the STB application, by calling
 *            \c dvlReleaseBuffer().
 *
 *  @retval DVL_NO_ERROR
 *            The function execution was successful.
 *  @retval DVL_ERROR
 *            The function execution failed.
 *  @retval DVL_ERROR_BAD_PARAMETER
 *            One or more arguments of the function are invalid or missing.
 *  @retval DVL_ERROR_DVL_NOT_RUNNING
 *            The function could not be executed as the DVR/VOD Library is not
 *            running.
 *
 *  @see ::dvlReleaseBuffer()
*/
NAGRA_CA_API TDvlStatus dvlCredentialsInformationRequest
(
        TSize                 xCredentialsSize,
  const TUnsignedInt8*       pxCredentials,
        TCredentialsType*    pxCredentialsType,
  const TCredentialsUnion** ppxCredentialsUnion,
        TSize*               pxGenericMetadataSize,
  const TUnsignedInt8**     ppxGenericMetadata,
        TSize*               pxSpecificMetadataSize,
  const TUnsignedInt8**     ppxSpecificMetadata
);

#ifdef __cplusplus
}
#endif

#endif /* NV_INFO_H */

/* END OF FILE */
