#ifndef PRMAPIVR_H
#define PRMAPIVR_H
/* Generated by buildRevFileP4.py */
/* Information extracted from ../.././components/prmapi/p4codeline.xml */
/* P4 Path : //CAK/components/prmapi/TAGS/PRMAPI_3_5_7 */
/* Last version: PRMAPI_3_5_7 */
#define PRMAPI_RELEASE "3.5.7"
#define PRMAPI_NAME "PRMAPI"
#define PRMAPI_VERSION 003005007
#define PRMAPI_BRANCH 000000
#define PRMAPI_CANDIDATE 000
#endif /* PRMAPIVR_H */
