#ifndef CAKAPIVR_H
#define CAKAPIVR_H
/* Generated by buildRevFileP4.py */
/* Information extracted from ../.././components/cakapi/p4codeline.xml */
/* P4 Path : //CAK/components/cakapi/TAGS/CAKAPI_1_40_0 */
/* Last version: CAKAPI_1_40_0 */
#define CAKAPI_RELEASE "1.40.0"
#define CAKAPI_NAME "CAKAPI"
#define CAKAPI_VERSION 001040000
#define CAKAPI_BRANCH 000000
#define CAKAPI_CANDIDATE 000
#endif /* CAKAPIVR_H */
