#pragma once
s_service_category_map[45626][104] = { // 11720000/"Vertical"
    {238, static_cast<Service_Category>(13)}, // "Rádio Rede Super" - "Rádios"
    {372, static_cast<Service_Category>(2)}, // "TV Imaculada" - "Religioso"
    {374, static_cast<Service_Category>(8)}, // "TV Paraná Turismo" - "Entretenimento"
    {379, static_cast<Service_Category>(12)}, // "Inter TV Grande Minas" - "Regionais"
    {375, static_cast<Service_Category>(12)}, // "Rede Amazônica Rio Branco" - "Regionais"
    {376, static_cast<Service_Category>(12)}, // "Rede Amazônica Macapá" - "Regionais"
    {377, static_cast<Service_Category>(12)}, // "Rede Amazônica Porto Velho" - "Regionais"
    {378, static_cast<Service_Category>(12)}, // "Rede Amazônica Boa Vista" - "Regionais"
    {384, static_cast<Service_Category>(12)}, // "TV Alvorada do Sul" - "Regionais"
    {380, static_cast<Service_Category>(12)}, // "Inter TV Costa Branca" - "Regionais"
    {385, static_cast<Service_Category>(12)}, // "AMAZON SAT" - "Regionais"
    {381, static_cast<Service_Category>(12)}, // "TV Santa Cruz" - "Regionais"
    {382, static_cast<Service_Category>(12)}, // "TV Sudoeste" - "Regionais"
    {383, static_cast<Service_Category>(12)}, // "TV Clube Teresina" - "Regionais"
    {386, static_cast<Service_Category>(12)}, // "AMAZON SAT - AC" - "Regionais"
    {389, static_cast<Service_Category>(12)}, // "Record Rondônia" - "Regionais"
    {373, static_cast<Service_Category>(12)}, // "TV Aratu" - "Regionais"
    {387, static_cast<Service_Category>(12)}, // "TV Jangadeiro" - "Regionais"
    {388, static_cast<Service_Category>(12)}, // "TV Serra Dourada" - "Regionais"
};
s_service_category_map[45626][103] = { // 12000000/"Vertical"
    {399, static_cast<Service_Category>(13)}, // "Rádio Novo Tempo" - "Rádios"
    {347, static_cast<Service_Category>(2)}, // "Rede Super" - "Religioso"
    {349, static_cast<Service_Category>(2)}, // "Rede Gospel" - "Religioso"
    {358, static_cast<Service_Category>(12)}, // "Band Taubaté" - "Regionais"
    {365, static_cast<Service_Category>(13)}, // "EVANGELIZAR FM" - "Rádios"
    {352, static_cast<Service_Category>(13)}, // "FM 93 MHZ" - "Rádios"
    {364, static_cast<Service_Category>(13)}, // "RÁDIO VERDES MARES" - "Rádios"
    {345, static_cast<Service_Category>(2)}, // "Boa Vontade TV" - "Religioso"
    {362, static_cast<Service_Category>(9)}, // "Canal do Boi" - "Agronegócio"
    {363, static_cast<Service_Category>(9)}, // "Agro Canal" - "Agronegócio"
    {346, static_cast<Service_Category>(9)}, // "Canal Rural" - "Agronegócio"
    {353, static_cast<Service_Category>(9)}, // "Canal do Criador" - "Agronegócio"
    {350, static_cast<Service_Category>(16)}, // "Gazin" - "Compras"
    {368, static_cast<Service_Category>(13)}, // "Radio Gospel" - "Rádios"
    {390, static_cast<Service_Category>(13)}, // "Band News FM" - "Rádios"
    {391, static_cast<Service_Category>(13)}, // "Rádio Bandeirantes FM" - "Rádios"
    {392, static_cast<Service_Category>(13)}, // "Band FM" - "Rádios"
    {393, static_cast<Service_Category>(13)}, // "Nativa FM" - "Rádios"
    {359, static_cast<Service_Category>(12)}, // "Band Pres. Prudente" - "Regionais"
    {805, static_cast<Service_Category>(4)}, // "TESTE 15" - "Novos canais"
    {348, static_cast<Service_Category>(12)}, // "NSC TV" - "Regionais"
    {360, static_cast<Service_Category>(12)}, // "Band Manaus" - "Regionais"
    {356, static_cast<Service_Category>(12)}, // "Band Paraná" - "Regionais"
    {355, static_cast<Service_Category>(12)}, // "Band Porto Alegre" - "Regionais"
    {357, static_cast<Service_Category>(12)}, // "Band Campinas" - "Regionais"
    {351, static_cast<Service_Category>(12)}, // "TV Verdes Mares Cariri" - "Regionais"
    {361, static_cast<Service_Category>(12)}, // "Band Ceará" - "Regionais"
};
s_service_category_map[45626][150] = { // 12580000/"Horizontal"
    {425, static_cast<Service_Category>(11)}, // "Canal GOV" - "TV Pública"
    {164, static_cast<Service_Category>(11)}, // "TV Brasil" - "TV Pública"
    {160, static_cast<Service_Category>(11)}, // "TV Justiça" - "TV Pública"
    {161, static_cast<Service_Category>(11)}, // "TV Senado" - "TV Pública"
};
s_service_category_map[45626][114] = { // 11860000/"Horizontal"
    {1099, static_cast<Service_Category>(8)}, // "Melphis TV" - "Entretenimento"
    {1100, static_cast<Service_Category>(2)}, // "Igreja Mundial/IMPD" - "Religioso"
    {1098, static_cast<Service_Category>(8)}, // "RF TV" - "Entretenimento"
    {1101, static_cast<Service_Category>(8)}, // "Rede Gazeta Brasil" - "Entretenimento"
    {1095, static_cast<Service_Category>(11)}, // "TVE BAHIA" - "TV Pública"
    {1077, static_cast<Service_Category>(9)}, // "BRTVMAX" - "Agronegócio"
    {1087, static_cast<Service_Category>(15)}, // "Times Brasil / CNBC" - "Notícias"
    {1094, static_cast<Service_Category>(12)}, // "Record RIC TV" - "Regionais"
    {1097, static_cast<Service_Category>(12)}, // "TV RECORD NACIONAL " - "Regionais"
    {1078, static_cast<Service_Category>(12)}, // "Record Uberlândia" - "Regionais"
    {1085, static_cast<Service_Category>(12)}, // "TH+ BAND HD" - "Regionais"
};
s_service_category_map[45626][101] = { // 12120000/"Vertical"
    {316, static_cast<Service_Category>(2)}, // "REDE VIDA" - "Religioso"
    {307, static_cast<Service_Category>(2)}, // "TV Novo Tempo" - "Religioso"
    {312, static_cast<Service_Category>(8)}, // "REDETV" - "Entretenimento"
    {309, static_cast<Service_Category>(12)}, // "SBT RIO" - "Regionais"
    {318, static_cast<Service_Category>(2)}, // "TV CANÇÃO NOVA" - "Religioso"
    {320, static_cast<Service_Category>(2)}, // "TV HORIZONTE" - "Religioso"
    {310, static_cast<Service_Category>(8)}, // "Xsports" - "Entretenimento"
    {302, static_cast<Service_Category>(8)}, // "TV Diário - Fortaleza" - "Entretenimento"
    {314, static_cast<Service_Category>(12)}, // "TV TEM HD BAURU" - "Regionais"
    {319, static_cast<Service_Category>(12)}, // "Amazon Sat - Nacional" - "Regionais"
    {303, static_cast<Service_Category>(12)}, // "EPTV Varginha" - "Regionais"
    {313, static_cast<Service_Category>(12)}, // "SBT BSB" - "Regionais"
    {306, static_cast<Service_Category>(12)}, // "TV Morena" - "Regionais"
    {305, static_cast<Service_Category>(12)}, // "TV Mirante" - "Regionais"
    {304, static_cast<Service_Category>(12)}, // "TV Centro América" - "Regionais"
    {311, static_cast<Service_Category>(15)}, // "RECORD NEWS" - "Notícias"
};
s_service_category_map[45626][166] = { // 12460000/"Horizontal"
    {456, static_cast<Service_Category>(12)}, // "TV Verdes Mares HD Fortaleza" - "Regionais"
    {454, static_cast<Service_Category>(12)}, // "Globo RJ HD" - "Regionais"
    {455, static_cast<Service_Category>(12)}, // "Globo SP HD" - "Regionais"
    {457, static_cast<Service_Category>(12)}, // "TV Bahia HD" - "Regionais"
};
s_service_category_map[45626][105] = { // 12180000/"Horizontal"
    {816, static_cast<Service_Category>(4)}, // "Canal de Teste 916" - "Novos canais"
    {8416, static_cast<Service_Category>(4)}, // "Canal de Teste 920" - "Novos canais"
    {821, static_cast<Service_Category>(4)}, // "Teste 921" - "Novos canais"
};
s_service_category_map[45626][164] = { // 12420000/"Horizontal"
    {458, static_cast<Service_Category>(12)}, // "Globo HD Minas" - "Regionais"
    {459, static_cast<Service_Category>(12)}, // "Globo Nordeste HD" - "Regionais"
    {465, static_cast<Service_Category>(12)}, // "TV Liberal HD Belém" - "Regionais"
};
s_service_category_map[45626][102] = { // 11940000/"Horizontal"
    {324, static_cast<Service_Category>(9)}, // "Terra Viva" - "Agronegócio"
    {323, static_cast<Service_Category>(2)}, // "Rede 21" - "Religioso"
    {331, static_cast<Service_Category>(2)}, // "PAI ETERNO" - "Religioso"
    {337, static_cast<Service_Category>(12)}, // "BAND BA" - "Regionais"
    {336, static_cast<Service_Category>(12)}, // "BAND MG" - "Regionais"
    {329, static_cast<Service_Category>(2)}, // "EVANGELIZAR" - "Religioso"
    {334, static_cast<Service_Category>(8)}, // "Rede Gazeta SP" - "Entretenimento"
    {332, static_cast<Service_Category>(8)}, // "REDE CNT" - "Entretenimento"
    {333, static_cast<Service_Category>(8)}, // "CNT RJ" - "Entretenimento"
    {335, static_cast<Service_Category>(15)}, // "JOVEM PAN NEWS" - "Notícias"
    {325, static_cast<Service_Category>(12)}, // "SBT" - "Regionais"
    {321, static_cast<Service_Category>(12)}, // "BAND SAT" - "Regionais"
    {340, static_cast<Service_Category>(12)}, // "SBT RS" - "Regionais"
    {322, static_cast<Service_Category>(12)}, // "BAND SP" - "Regionais"
    {344, static_cast<Service_Category>(12)}, // "SBT SP" - "Regionais"
    {343, static_cast<Service_Category>(12)}, // "BAND RJ" - "Regionais"
    {330, static_cast<Service_Category>(2)}, // "Rede Cristã" - "Religioso"
};
s_service_category_map[45626][111] = { // 11740000/"Horizontal"
    {1096, static_cast<Service_Category>(13)}, // "Rádio Verdes Campos" - "Rádios"
    {1068, static_cast<Service_Category>(2)}, // "RIT" - "Religioso"
    {1013, static_cast<Service_Category>(2)}, // "REDEVIDA EDUCAÇÃO" - "Religioso"
    {1016, static_cast<Service_Category>(2)}, // "TV Mundo Maior" - "Religioso"
    {1010, static_cast<Service_Category>(2)}, // "TV TEMPLO" - "Religioso"
    {1011, static_cast<Service_Category>(2)}, // "TV PADRE CICERO" - "Religioso"
    {1027, static_cast<Service_Category>(13)}, // "MEIO NORTE FM" - "Rádios"
    {1029, static_cast<Service_Category>(13)}, // "Rede Mensageiros da Paz" - "Rádios"
    {1048, static_cast<Service_Category>(13)}, // "Rádio Maanaim" - "Rádios"
    {1005, static_cast<Service_Category>(13)}, // "SAUDADE FM" - "Rádios"
    {1006, static_cast<Service_Category>(13)}, // "APARECIDA FM" - "Rádios"
    {1007, static_cast<Service_Category>(13)}, // "REDE VIDA FM" - "Rádios"
    {1021, static_cast<Service_Category>(13)}, // "Radio Boa Nova" - "Rádios"
    {1053, static_cast<Service_Category>(13)}, // "Rádio ISFM" - "Rádios"
    {1072, static_cast<Service_Category>(13)}, // "MELPHIS FM" - "Rádios"
    {1079, static_cast<Service_Category>(13)}, // "Nery FM" - "Rádios"
    {1086, static_cast<Service_Category>(13)}, // "Rádio Nova Brasil" - "Rádios"
    {1003, static_cast<Service_Category>(2)}, // "TV APARECIDA" - "Religioso"
    {1012, static_cast<Service_Category>(2)}, // "REDEVIDA MAIS" - "Religioso"
    {1004, static_cast<Service_Category>(8)}, // "ISTV" - "Entretenimento"
    {1008, static_cast<Service_Category>(8)}, // "REDE BRASIL" - "Entretenimento"
    {1009, static_cast<Service_Category>(8)}, // "RBTV" - "Entretenimento"
    {1052, static_cast<Service_Category>(8)}, // "F11 TV" - "Entretenimento"
    {1001, static_cast<Service_Category>(10)}, // "TV CULTURA" - "Educação"
    {1024, static_cast<Service_Category>(15)}, // "CNN BRASIL" - "Notícias"
    {1081, static_cast<Service_Category>(15)}, // "Auto Mais TV" - "Notícias"
    {1025, static_cast<Service_Category>(16)}, // "POLISHOP" - "Compras"
    {1083, static_cast<Service_Category>(12)}, // "Record THATHI Campinas" - "Regionais"
    {1018, static_cast<Service_Category>(12)}, // "SBT Belem" - "Regionais"
};
s_service_category_map[45626][169] = { // 12560000/"Vertical"
    {467, static_cast<Service_Category>(12)}, // "Rede Amazônica Manaus HD" - "Regionais"
    {479, static_cast<Service_Category>(12)}, // "EPTV HD Campinas" - "Regionais"
};
s_service_category_map[45626][107] = { // 12140000/"Horizontal"
    {818, static_cast<Service_Category>(4)}, // "Canal de Teste" - "Novos canais"
};
s_service_category_map[45626][113] = { // 11820000/"Horizontal"
    {1092, static_cast<Service_Category>(13)}, // "Rádio Câmara" - "Rádios"
    {1091, static_cast<Service_Category>(11)}, // "TV Câmara" - "TV Pública"
    {1054, static_cast<Service_Category>(12)}, // "Record RS" - "Regionais"
    {1058, static_cast<Service_Category>(12)}, // "Record Paulista" - "Regionais"
    {1055, static_cast<Service_Category>(12)}, // "Record Belém" - "Regionais"
    {1059, static_cast<Service_Category>(12)}, // "Record Manaus" - "Regionais"
    {1061, static_cast<Service_Category>(12)}, // "Record Litoral e Vale" - "Regionais"
    {1065, static_cast<Service_Category>(12)}, // "Record Franca e Ribeirao Preto" - "Regionais"
    {1070, static_cast<Service_Category>(12)}, // "Record TV Cidade Fortaleza" - "Regionais"
    {1056, static_cast<Service_Category>(12)}, // "Record Goiás" - "Regionais"
    {1071, static_cast<Service_Category>(12)}, // "Record Piauí A10" - "Regionais"
    {1057, static_cast<Service_Category>(12)}, // "Record Bahia" - "Regionais"
    {1060, static_cast<Service_Category>(12)}, // "Record Rio" - "Regionais"
    {1067, static_cast<Service_Category>(12)}, // "Record BH" - "Regionais"
    {1076, static_cast<Service_Category>(12)}, // "SBT TV NORTE" - "Regionais"
    {1073, static_cast<Service_Category>(12)}, // "Record Paraíba TV Correio" - "Regionais"
    {1090, static_cast<Service_Category>(12)}, // "SBT Ponta Verde" - "Regionais"
    {1082, static_cast<Service_Category>(12)}, // "Record TV LESTE" - "Regionais"
    {1089, static_cast<Service_Category>(12)}, // "Record Guararapes" - "Regionais"
};
s_service_category_map[45626][167] = { // 12480000/"Vertical"
    {460, static_cast<Service_Category>(12)}, // "TV Anhanguera Goiania HD" - "Regionais"
    {464, static_cast<Service_Category>(12)}, // "RPC TV Curitiba HD" - "Regionais"
    {466, static_cast<Service_Category>(12)}, // "RBS TV HD Porto Alegre" - "Regionais"
    {687, static_cast<Service_Category>(10)}, // "Futura HD" - "Educação"
};
s_service_category_map[45626][106] = { // 11900000/"Horizontal"
    {497, static_cast<Service_Category>(2)}, // "RBI - REDE BRASILEIRA DE INTEGRAÇÃO" - "Religioso"
    {498, static_cast<Service_Category>(8)}, // "UMA TV" - "Entretenimento"
    {488, static_cast<Service_Category>(12)}, // "TV ALTEROSA JUIZ DE FORA" - "Regionais"
    {492, static_cast<Service_Category>(12)}, // "TV CABO BRANCO" - "Regionais"
    {496, static_cast<Service_Category>(15)}, // "TVT NEWS" - "Notícias"
    {493, static_cast<Service_Category>(15)}, // "TVD NEWS" - "Notícias"
    {817, static_cast<Service_Category>(4)}, // "Canal de Teste" - "Novos canais"
    {483, static_cast<Service_Category>(12)}, // "TV SUBAÉ" - "Regionais"
    {487, static_cast<Service_Category>(12)}, // "TV ALTEROSA LESTE" - "Regionais"
    {484, static_cast<Service_Category>(12)}, // "TV OESTE" - "Regionais"
    {485, static_cast<Service_Category>(12)}, // "TV SÃO FRANCISCO" - "Regionais"
    {486, static_cast<Service_Category>(12)}, // "TV Sergipe" - "Regionais"
    {489, static_cast<Service_Category>(12)}, // "TV ALTEROSA DIVINOPOLIS" - "Regionais"
    {494, static_cast<Service_Category>(12)}, // "Rede Amazônica Ariquemes" - "Regionais"
    {490, static_cast<Service_Category>(12)}, // "TV ALTEROSA INTERIOR" - "Regionais"
    {491, static_cast<Service_Category>(12)}, // "TV ANHANGUERA PALMAS" - "Regionais"
    {495, static_cast<Service_Category>(12)}, // "TV Alterosa Varginha" - "Regionais"
    {500, static_cast<Service_Category>(11)}, // "TV Assembleia de Minas" - "TV Pública"
    {502, static_cast<Service_Category>(13)}, // "Rádio Canção Nova - 89.1" - "Rádios"
    {501, static_cast<Service_Category>(13)}, // "Canção Nova FM - 96.3" - "Rádios"
};
s_service_category_map[45626][112] = { // 11780000/"Horizontal"
    {1049, static_cast<Service_Category>(8)}, // "Masper TV" - "Entretenimento"
    {1045, static_cast<Service_Category>(2)}, // "Igreja Cristã Maranata" - "Religioso"
    {1033, static_cast<Service_Category>(2)}, // "TV VERDADE" - "Religioso"
    {1042, static_cast<Service_Category>(11)}, // "PT Sat" - "TV Pública"
    {1093, static_cast<Service_Category>(12)}, // "Record TV Atalaia" - "Regionais"
    {1039, static_cast<Service_Category>(8)}, // "PlayTV Mais" - "Entretenimento"
    {1044, static_cast<Service_Category>(8)}, // "YPÊ TV" - "Entretenimento"
    {1032, static_cast<Service_Category>(8)}, // "TV MANÁ BRASIL" - "Entretenimento"
    {1030, static_cast<Service_Category>(8)}, // "TV MEIO NORTE" - "Entretenimento"
    {1034, static_cast<Service_Category>(8)}, // "SBN" - "Entretenimento"
    {1035, static_cast<Service_Category>(8)}, // "VIVAX TV" - "Entretenimento"
    {1031, static_cast<Service_Category>(9)}, // "TV MILAGRO BRASIL" - "Agronegócio"
    {1080, static_cast<Service_Category>(15)}, // "CANAL UOL" - "Notícias"
    {1088, static_cast<Service_Category>(15)}, // "Record News MG/GO" - "Notícias"
    {1046, static_cast<Service_Category>(16)}, // "TV Ultrafarma" - "Compras"
    {1037, static_cast<Service_Category>(12)}, // "TV Tribuna Recife" - "Regionais"
    {1075, static_cast<Service_Category>(12)}, // "SBT - Campinas - Santos - VTV" - "Regionais"
    {1084, static_cast<Service_Category>(12)}, // "TV THATHI SBT" - "Regionais"
};
